sudo: required
services:
  - docker

before_install:
  - docker build -t jtabach/docker-react -f Dockerfile.dev .

script:
  - docker run jtabach/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'docker-react'
  env: 'DockerReact-env-1'
  bucket_name: 'elasticbeanstalk-us-west-2-008006857784'
  bucket_path: 'docker-react'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: '$AWS_SECRET_KEY'
